-- V3: Advanced CRM fields and Envers Auditing Tables

-- 1. Advance CRM Fields for Leads
ALTER TABLE leads ADD COLUMN assigned_to UUID REFERENCES users(id);
ALTER TABLE leads ADD COLUMN internal_notes TEXT;

-- We also need to update the constraint for lead statuses, but PostgreSQL doesn't allow adding to an existing check constraint easily without replacing it.
ALTER TABLE leads DROP CONSTRAINT leads_status_check;
ALTER TABLE leads ADD CONSTRAINT leads_status_check CHECK (status IN ('NUEVO','CONTACTADO','EN_SEGUIMIENTO','REUNION_AGENDADA','CERRADO_GANADO','CERRADO_PERDIDO'));

-- 2. Hibernate Envers Revision Table
CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- 3. Audit table for Projects
CREATE TABLE projects_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    name VARCHAR(200),
    slug VARCHAR(250),
    short_description VARCHAR(500),
    long_description TEXT,
    status VARCHAR(30),
    min_price DECIMAL(15,2),
    max_price DECIMAL(15,2),
    estimated_delivery DATE,
    address VARCHAR(500),
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    is_featured BOOLEAN,
    is_published BOOLEAN,
    meta_title VARCHAR(200),
    meta_description VARCHAR(500),
    city_id UUID,
    neighborhood_id UUID,
    deleted_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    PRIMARY KEY (id, rev)
);

-- 4. Audit table for Properties
CREATE TABLE properties_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    project_id UUID,
    name VARCHAR(200),
    type VARCHAR(30),
    built_area DECIMAL(10,2),
    private_area DECIMAL(10,2),
    bedrooms INT,
    bathrooms INT,
    parking_spots INT,
    stratum INT,
    price DECIMAL(15,2),
    status VARCHAR(20),
    floor_or_tower VARCHAR(50),
    deleted_at TIMESTAMP,
    created_by UUID,
    updated_by UUID,
    PRIMARY KEY (id, rev)
);

-- 5. Audit table for Company Info
CREATE TABLE company_info_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    name VARCHAR(200),
    about_us TEXT,
    mission TEXT,
    vision TEXT,
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    contact_address VARCHAR(500),
    logo_url VARCHAR(500),
    created_by UUID,
    updated_by UUID,
    PRIMARY KEY (id, rev)
);

-- 6. Audit table for Leads
CREATE TABLE leads_aud (
    id UUID NOT NULL,
    rev INTEGER NOT NULL REFERENCES revinfo(rev),
    revtype SMALLINT,
    full_name VARCHAR(200),
    email VARCHAR(255),
    phone VARCHAR(30),
    message TEXT,
    origin VARCHAR(50),
    status VARCHAR(20),
    data_consent BOOLEAN,
    honeypot VARCHAR(255),
    project_id UUID,
    assigned_to UUID,
    internal_notes TEXT,
    updated_by UUID,
    PRIMARY KEY (id, rev)
);
